### PR TITLE
Reorganise functions

### PR DESCRIPTION
**Pull request by ltratt**
This PR aims to sort out the internal representation of SOM functions. The basic problem is that we previously had quite separate representations of SOM methods and blocks, and that hinders o. The major work is done in https://github.com/softdevteam/yksom/commit/9cbe414650907d79366d4f30db6c7486d8148f0e (https://github.com/softdevteam/yksom/commit/cb5b342d35032008ac332d8c7c0c967a5075459d is a simple stand-alone improvement).

### CODE REVIEW

**Comment by ptersilie** [comment]
Just some possible typos:
> causing an internal awkward API
extra intenal here?

> and open up future optimisation
s/open/opens

> track all a function's blocks
s/all/all of

**Comment by ltratt** [comment]
OK for me to force push?

**Comment by ptersilie** [comment]
Please do.

**Comment by ltratt** [comment]
Force pushed.

**Pull request merged**
