### PR TITLE
Unassigned instance variables should print 'nil'.

### PR DESCRIPTION
**Pull request by ltratt**

### CODE REVIEW

**Comment by ltratt** [comment]
I forgot to say: with this PR, all the SOM benchmarks run.

**Comment by vext01** [comment]
That's cool!

**Comment by smarr** [comment]
Yay :)

**Comment by ltratt** [comment]
Don't expect too much though -- they're a bit slow at the moment! For example:

```
Benchmark: Fibonacci                                                   [113/886]
   Iterations: 6 (elapsed time 3165 ms)                                        
   AVERAGE: 527 ms                                                             
                                                                               
Starting Dispatch benchmark ...  warmup ... completed.                         
                                                      
Benchmark: Dispatch                                    
   Iterations: 11 (elapsed time 3130 ms)
   AVERAGE: 285 ms                                 
                                        
Starting Bounce benchmark ...  warmup ... completed.
                                                    
Benchmark: Bounce
   Iterations: 8 (elapsed time 3359 ms)
   AVERAGE: 420 ms

Starting Loop benchmark ...  warmup ... completed.

Benchmark: Loop
   Iterations: 8 (elapsed time 3230 ms)
   AVERAGE: 404 ms
```

Turning off GC makes a massive difference:

```
Benchmark: Fibonacci                                                           
   Iterations: 36 (elapsed time 3044 ms)                                       
   AVERAGE: 85 ms                                                              
                                                                               
Starting Dispatch benchmark ...  warmup ... completed.

Benchmark: Dispatch
   Iterations: 49 (elapsed time 3002 ms)
   AVERAGE: 61 ms

Starting Bounce benchmark ...  warmup ... completed.

Benchmark: Bounce
   Iterations: 66 (elapsed time 3012 ms)
   AVERAGE: 46 ms

Starting Loop benchmark ...  warmup ... completed.

Benchmark: Loop
   Iterations: 36 (elapsed time 3004 ms)
   AVERAGE: 83 ms
```

Roughly speaking, it looks like we're spending 80-90% of time in GC. That will surely improve when @jacob-hughes gets on this after his internship, but it's not going to happen tomorrow.

**Pull request merged**
