### PR TITLE
Simplify casting.

### PR DESCRIPTION
**Pull request by ltratt**
This is a deceptively simple PR and I can't believe it didn't occur to me earlier. In essence, we add a new trait `NotUnboxable` which if implemented for a SOM object means "this struct can never be unboxed". In our case, we implement this trait for everything except `Int`s. If you want to downcast a `Val` to a given `NotUnboxable` object type you can then change:

```
    let str_tobj = rcv.tobj(self)?;
    let str_: &String_ = downcast(&str_tobj)?;
```

into:

```
    let str_: &String_ = rcv.gcbox_downcast(vm)?;
```

Not only is this much simpler to write and read, but a) we can now statically detect when you're trying to do an illegal `gcbox_downcast` (e.g. you get a compile-time error if you try to downcast to an `Int`) b) we remove a check and branch from the performance critical `gcbox_downcas` function. So this seems like a win all round!

### CODE REVIEW

**Comment by vext01** [comment]
After getting over the initial upside-down thinking phase, this seems sensible to me. The added static checking is definitely good!

**Comment by ltratt** [comment]
Originally I had hoped to use negative trait bounds (so every `Obj` would be boxable unless you explicitly opted out) but those simply aren't implemented fully enough.

I should have given a tip of the hat to @jacob-hughes here, because the `NotTrait` idea is vaguely based on ideas he had/has in his GC trait. I agree that it seems a bit upside-down at first!

**Comment by vext01** [comment]
Unless you want input from @jacob-hughes(?), I'll merge this.

**Comment by ltratt** [comment]
No input needed from him -- just me saying thanks!

**Comment by jacob-hughes** [comment]
LGTM anyway :)

**Pull request merged**
