### PR TITLE
Use external SOM lib as a submodule

### PR DESCRIPTION
**Pull request by ltratt**
This uses the "real" SOM library as a submodule. I expect this will take some fiddling to get it to work with buildbot, so we might need some help from @vext01.

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
bors try

**Comment by smarr** [comment]
👍 for the change
👎 for the quotes around real 😉 

Would be nice to see the output of the equivalent of `./som -cp Smalltalk TestSuite/TestHarness.som`.
And perhaps the basic interpreter tests: https://github.com/SOM-st/SOM/tree/master/TestSuite/BasicInterpreterTests

Afterwards, `./som -cp Smalltalk:Examples/Benchmarks/LanguageFeatures Examples/Benchmarks/All.som` would be great :)

**Comment by ltratt** [comment]
It's not even close to being able to run the test harness!

**Comment by smarr** [comment]
Hm, what are the major obstacles? You got class loading. So, I guess it's primitives? You need a little reflection for the harness, which is probably two primitives. Anything else?

**Comment by ltratt** [comment]
I don't know what I don't know: yksom is strictly one step at a time ;)

**Comment by ltratt** [comment]
@ptersilie I think @vext01 and I have decided that we'll leave it to `.buildbot.sh` to pull in the submodules, at which point I think this PR is ready for squashing.

**Comment by ptersilie** [comment]
Ok, please squash.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
