### PR TITLE
Adjust to the new natrob API that returns Gc from downcast.

### PR DESCRIPTION
**Pull request by ltratt**
This reflects the change in https://github.com/softdevteam/natrob/pull/14#issuecomment-635622030.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
All LGTM. As a general observation with this stuff, It looks like you will (or are just about to) run into the need for arbitrary self types. I am pretty sure I did this when doing the API for gcmalloc (but can't remember now). Has that been working ok?

**Comment by ltratt** [comment]
I don't *think* I'll need arbitrary self types here (though I would love them to work fully in some other contexts!).

**Comment by jacob-hughes** [comment]
Cool. I'm interested to see how well it works.

**Comment by ltratt** [comment]
> Cool. I'm interested to see how well it works.

So am I!

**Comment by ltratt** [comment]
A reminder to self: test everything fully before making a PR. The problem that caused the buildbot failure is fixed in https://github.com/softdevteam/natrob/pull/15. Once that's merged, this PR should build.

**Pull request merged**
