### PR TITLE
Add Fibonacci test.

### PR DESCRIPTION
**Pull request by ltratt**
As suggested by @smarr in https://github.com/softdevteam/yksom/pull/77#issuecomment-555062043. The test passes fine.

### CODE REVIEW

**Comment by ltratt** [comment]
bors try

**Comment by ltratt** [comment]
@smarr Hopefully the `fib` test succeeding is a decent indication that this part works OK? I must admit, I wasn't even sure if yksom had all the bits it needed for such a test, but it turns out that it does. I should have added it ages ago!

**Comment by ptersilie** [comment]
Looks good. If @smarr is happy, I will merge.

**Comment by smarr** [comment]
Yeah, I was just concerned about how many program counters there can be for a block/method.
There need to be `n` program counters, where `n` is the number of activations of the block/method, which I suppose is checked by the test. If it wouldn't, I'd expect an infinite loop, I think.

In terms of language features, I don't think it uses anything I haven't seen in your tests before.

**Pull request merged**
