### PR TITLE
Call the System initialize: method

### PR DESCRIPTION
**Pull request by ltratt**
SOM runs programs by calling the `initialize:` method in `System.som` and having it load the user's class. This PR makes SOM do just this (https://github.com/softdevteam/yksom/commit/f942f274ae51c1f4faf4c6c41704ed771aa92e26). To get to that point, we have to do various bits of preparatory work, notably supporting the `methods` (https://github.com/softdevteam/yksom/commit/c64f237c2e3fcc70b957e0d59013b6ec902b8ece) and `signature` (https://github.com/softdevteam/yksom/commit/926cd5ef280fc380640e8a7bd3b7d649565f41c3) primitives.

Note that the `methods` primitive exposes a mutable array and we are thus currently subject to the same flaw as Java SOM in this regard (see https://github.com/SOM-st/SOM/issues/35). Fixing that is for a later PR.

### CODE REVIEW

**Comment by ptersilie** [comment]
There's two typos in the last commit:
> SOM starts programs by running by calling the initialize:

>bootstraping

**Comment by ptersilie** [comment]
Rest looks good.

**Comment by ltratt** [comment]
@ptersilie Should I force push? [If you don't tell me to, I don't know that I can!]

**Comment by ptersilie** [comment]
Sorry, of course. Please do a force push.

**Comment by ltratt** [comment]
Updated and force pushed.

**Pull request merged**
