### PR TITLE
Fix class names.

### PR DESCRIPTION
**Pull request by ltratt**
SOM class names should match the file name.

### CODE REVIEW

**Comment by smarr** [comment]
Risking just being annoying:

**Class names should be capitalized** in any Smalltalk, and SOM.
Also, numbering classes is likely to mean that the code is less maintainable, because noone remembers what the difference between the classes were intended to be.

**Comment by ltratt** [comment]
The comment is a fair one. I have a deep personal distaste for capital letters in file names verging on the pathological -- I can't help it! I can't bring myself to change the file names, but if someone else fixes them, I will merge it happily.

The "numbers as part of names" thing is true, but it's often *really* hard to think of meaningful names for so many tests. I agree that we should probably try a bit harder than we do, but I'm realistic that we'd always end up with *some* numbers in names.

**Comment by ptersilie** [comment]
> I have a deep personal distaste for capital letters in file names verging on the pathological

I hope you'll never have to write Java then. ;-)

**Pull request merged**
