### PR TITLE
Fix double/int comparisons.

### PR DESCRIPTION
**Pull request by ltratt**
Note that these further diverge from Java SOM, where the following:

```
  (1.0 = 1) println.
  (1.0 ~= 1) println.
```

prints:

```
  true
  true
```

whereas yksom prints:

```
  true
  false
```

### CODE REVIEW

**Comment by smarr** [comment]
Not sure, but you may run into issues with the benchmarks with this.

**Comment by vext01** [comment]
Do I see it right that `1.0` is both equal and not equal to `1`?

`~=` is "not equal" as in smalltalk?

**Comment by ltratt** [comment]
> Do I see it right that 1.0 is both equal and not equal to 1?

In Java SOM, yes, it's not symmetric. In yksom it is symmetric.

**Comment by ltratt** [comment]
> Not sure, but you may run into issues with the benchmarks with this.

OK, I'll keep an eye open!

**Pull request merged**
