### PR TITLE
Remove libgc

### PR DESCRIPTION
**Pull request by jacob-hughes**

### CODE REVIEW

**Comment by jacob-hughes** [comment]
This can be merged once https://github.com/softdevteam/rustgc/pull/35 lands.

**Comment by jacob-hughes** [comment]
Oops! Fixed: 17d6a65dc79a3b16ee79cf8a2d59832543e44951

**Comment by ltratt** [comment]
Please squash.

**Comment by jacob-hughes** [comment]
Squashed

**Pull request merged**
